import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  overlay: { flex: 1, backgroundColor: 'rgba(35, 30, 20, 0.42)' },
  safeContent: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 6 },
  card: { width: '100%', maxWidth: 440, maxHeight: '100%', backgroundColor: '#FFFCF2', borderRadius: 42, overflow: 'hidden' },
  cardContent: { paddingHorizontal: 30, paddingTop: 14, paddingBottom: 30 },
  close: { width: 52, height: 52, alignSelf: 'flex-end', marginBottom: 16 },
  closeIcon: { width: '100%', height: '100%' },
  headingRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginHorizontal: -12 },
  heading: { flexShrink: 1, color: '#512013', fontFamily: 'Inter_800ExtraBold', fontSize: 29, textAlign: 'center' },
  leaves: { width: 34, height: 34 },
  subtitle: { color: '#7D808A', fontFamily: 'Inter_400Regular', fontSize: 16, textAlign: 'center', marginTop: 3 },
  photoRow: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'center', marginTop: 20, marginBottom: 24 },
  avatarWrapper: { width: 118, height: 118 },
  avatarCircle: { width: 118, height: 118, borderRadius: 59, backgroundColor: '#FCE4DD', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  avatarIcon: { width: 90, height: 90 },
  photo: { width: '100%', height: '100%' },
  avatarLeaves: { width: 38, height: 42, marginBottom: 12 },
  camera: { position: 'absolute', bottom: 0, right: -8, width: 44, height: 44, borderRadius: 22, backgroundColor: '#FFFCF2', alignItems: 'center', justifyContent: 'center', boxShadow: '0px 2px 6px rgba(64,38,16,0.15)' },
  cameraIcon: { width: 20, height: 20 },
  field: { marginBottom: 20, gap: 6 },
  label: { color: '#512013', fontFamily: 'Inter_600SemiBold', fontSize: 13 },
  inputRow: { flexDirection: 'row', alignItems: 'center', minHeight: 44, backgroundColor: '#FFFFFF', borderRadius: 12, paddingHorizontal: 10, gap: 12, boxShadow: '0px 4px 10px rgba(64,38,16,0.08)' },
  inputIcon: { width: 24, height: 24 },
  input: { flex: 1, minWidth: 0, color: '#747985', fontFamily: 'Inter_400Regular', fontSize: 13, paddingVertical: 10 },
  error: { color: '#A12D28', fontFamily: 'Inter_400Regular', fontSize: 12, lineHeight: 18, marginBottom: 8 },
  actions: { gap: 12, marginTop: 6 },
  save: { minHeight: 44, borderRadius: 24, backgroundColor: '#FF5008', justifyContent: 'center', alignItems: 'center', paddingVertical: 10 },
  saveText: { color: '#FFFFFF', fontFamily: 'Inter_600SemiBold', fontSize: 13 },
  cancel: { minHeight: 44, borderRadius: 24, backgroundColor: '#F4D9CE', justifyContent: 'center', alignItems: 'center', paddingVertical: 10 },
  cancelText: { color: '#FF5008', fontFamily: 'Inter_600SemiBold', fontSize: 13 },
  pressed: { opacity: 0.65 },
});
