import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#FFFBF0" },
  content: {
    flexGrow: 1,
    alignItems: "center",
    paddingHorizontal: 22,
    paddingTop: 22,
    paddingBottom: 24,
  },
  page: { width: "100%", maxWidth: 390 },
  backButton: { width: 52, height: 52, zIndex: 1 },
  backIcon: { width: "100%", height: "100%" },
  brand: { alignItems: "center", marginTop: -18, marginBottom: 24 },
  logoRow: { width: "100%", flexDirection: "row", alignItems: "center" },
  chefHat: { width: "39%", aspectRatio: 143 / 141, marginRight: "-8%" },
  titleLogo: { width: "69%", aspectRatio: 250 / 106 },
  taglineRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "flex-end",
    width: "90%",
    marginTop: -6,
    marginBottom: 8,
  },
  taglineText: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 9,
    transform: [{ rotate: "-8deg" }],
  },
  taglineFirstLine: {
    color: "#5B1D12",
    fontFamily: "Lobster_400Regular",
    fontSize: 26,
    lineHeight: 30,
    textAlign: "center",
  },
  taglineSecondLine: {
    color: "#5B1D12",
    fontFamily: "Lobster_400Regular",
    fontSize: 26,
    lineHeight: 30,
    marginLeft: 24,
    textAlign: "center",
  },
  taglineHeart: {
    width: 40,
    height: 40,
    flexShrink: 0,
    marginLeft: 5,
    transform: [{ rotate: "8deg" }],
  },
  chef: { width: "90%", aspectRatio: 580 / 410 },
  headingRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    marginTop: 3,
  },
  heading: {
    color: "#5B1D12",
    fontFamily: "Inter_800ExtraBold",
    fontSize: 29,
    lineHeight: 38,
    flexShrink: 1,
    textAlign: "center",
  },
  headingLeaves: { width: 32, height: 38 },
  accounts: { gap: 14 },
  accountCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    minHeight: 94,
    paddingVertical: 16,
    paddingHorizontal: 14,
    backgroundColor: "#FFFFFF",
    borderRadius: 22,
    boxShadow: "0px 4px 10px rgba(64, 38, 16, 0.09)",
  },
  avatar: { width: 60, height: 60 },
  accountCopy: { flex: 1, gap: 7 },
  accountName: {
    color: "#512013",
    fontFamily: "Inter_800ExtraBold",
    fontSize: 16,
    lineHeight: 22,
  },
  accountEmail: {
    color: "#6D6D7B",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 18,
  },
  chevron: { width: 14, height: 20 },
  otherAccount: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    alignSelf: "center",
    width: "85%",
    minHeight: 54,
    paddingHorizontal: 12,
    paddingVertical: 9,
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#FF5008",
    borderRadius: 28,
  },
  plusIcon: { width: 32, height: 32 },
  otherAccountText: {
    color: "#FF5008",
    fontFamily: "Inter_600SemiBold",
    fontSize: 19,
    flexShrink: 1,
  },
  signupCard: {
    marginTop: 22,
    paddingHorizontal: 17,
    paddingTop: 12,
    paddingBottom: 15,
    backgroundColor: "#F8EFD3",
    borderRadius: 21,
    boxShadow: "0px 4px 10px rgba(64, 38, 16, 0.07)",
  },
  signupTitle: {
    color: "#512013",
    fontFamily: "Inter_800ExtraBold",
    fontSize: 17,
    lineHeight: 24,
  },
  signupRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 3,
  },
  signupDescription: {
    flex: 1,
    color: "#6D6D7B",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 19,
  },
  signupButton: { minHeight: 44, justifyContent: "center" },
  signupButtonText: {
    color: "#FF5008",
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#FF5008",
    borderRadius: 15,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  leftLeaves: {
    position: "absolute",
    width: 30,
    height: 42,
    left: -16,
    top: 11,
  },
  rightLeaves: {
    position: "absolute",
    width: 38,
    height: 38,
    right: -2,
    bottom: -7,
  },
  pressed: { opacity: 0.7 },
  notice: {
    color: "#512013",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 20,
    marginTop: 16,
  },
});

export function getLoginStyles(availableHeight: number) {
  if (availableHeight >= 900) return styles;

  return {
    ...styles,
    content: { ...styles.content, paddingTop: 10, paddingBottom: 14 },
    backButton: { ...styles.backButton, width: 44, height: 44 },
    brand: { ...styles.brand, marginBottom: 10 },
    logoRow: { ...styles.logoRow, width: "85%" as const },
    taglineRow: { ...styles.taglineRow, marginBottom: 4 },
    taglineText: { ...styles.taglineText, paddingVertical: 5 },
    taglineFirstLine: {
      ...styles.taglineFirstLine,
      fontSize: 24,
      lineHeight: 27,
    },
    taglineSecondLine: {
      ...styles.taglineSecondLine,
      fontSize: 24,
      lineHeight: 27,
    },
    chef: {
      ...styles.chef,
      width: "90%" as const,
      height: Math.max(96, Math.min(210, availableHeight - 602)),
      aspectRatio: undefined,
    },
    heading: { ...styles.heading, fontSize: 27, lineHeight: 34 },
    accounts: { ...styles.accounts, gap: 14 },
    accountCard: { ...styles.accountCard, minHeight: 72, paddingVertical: 10 },
    avatar: { ...styles.avatar, width: 48, height: 48 },
    accountCopy: { ...styles.accountCopy, gap: 4 },
    otherAccount: {
      ...styles.otherAccount,
      minHeight: 48,
      paddingVertical: 6,
      marginTop: 12,
    },
    signupCard: {
      ...styles.signupCard,
      marginTop: 16,
      paddingTop: 8,
      paddingBottom: 10,
    },
  };
}
