import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FFFCF2' },
  content: { flexGrow: 1, alignItems: 'center', paddingHorizontal: 12, paddingTop: 12, paddingBottom: 24 },
  page: { width: '100%', maxWidth: 430 },
  brandRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 8, marginBottom: 18 },
  logo: { width: '70%', flexDirection: 'row', alignItems: 'center' },
  hat: { width: '39%', aspectRatio: 143 / 141, marginRight: '-8%' },
  brandTitle: { width: '69%', aspectRatio: 250 / 106 },
  tagline: { width: '24%', minHeight: 84, justifyContent: 'center', alignItems: 'center', transform: [{ rotate: '-10deg' }] },
  taglineText: { color: '#512013', fontFamily: 'Lobster_400Regular', fontSize: 14, lineHeight: 16, textAlign: 'center', paddingVertical: 6 },
  taglineTopLeaves: { position: 'absolute', width: 19, height: 19, top: 0, right: 0 },
  taglineBottomLeaves: { position: 'absolute', width: 18, height: 18, bottom: 0, left: 0 },
  taglineHeart: { position: 'absolute', width: 16, height: 16, right: -3, bottom: 8 },
  headingRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20 },
  headingLeaves: { width: 36, height: 36 },
  heading: { color: '#512013', fontFamily: 'Inter_800ExtraBold', fontSize: 30, lineHeight: 38, textAlign: 'center' },
  subtitle: { color: '#85858D', fontFamily: 'Inter_600SemiBold', fontSize: 15, textAlign: 'center', marginTop: 2, marginBottom: 16 },
  profileCard: { flexDirection: 'row', alignItems: 'center', gap: 16, backgroundColor: '#FFF4D3', borderRadius: 24, paddingHorizontal: 18, paddingVertical: 22 },
  avatarWrapper: { width: 72, height: 76 },
  avatarCircle: { width: 72, height: 72, borderRadius: 36, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center' },
  avatar: { width: 52, height: 52 },
  editButton: { position: 'absolute', bottom: -6, right: -5, width: 28, height: 28, borderRadius: 14, backgroundColor: '#FFFCF2', alignItems: 'center', justifyContent: 'center', boxShadow: '0px 2px 5px rgba(64, 38, 16, 0.14)' },
  editIcon: { width: 16, height: 16 },
  profileCopy: { flex: 1 },
  profileTitle: { color: '#512013', fontFamily: 'Inter_800ExtraBold', fontSize: 20, marginBottom: 6 },
  profileDetail: { color: '#81818A', fontFamily: 'Inter_400Regular', fontSize: 12, lineHeight: 17 },
  optionsTitle: { color: '#512013', fontFamily: 'Inter_800ExtraBold', fontSize: 20, marginTop: 24, marginBottom: 8 },
  options: { gap: 18 },
  optionCard: { flexDirection: 'row', alignItems: 'center', gap: 15, backgroundColor: '#FFFFFF', borderRadius: 21, minHeight: 90, paddingHorizontal: 16, paddingVertical: 16, boxShadow: '0px 4px 9px rgba(64, 38, 16, 0.09)' },
  optionCircle: { width: 50, height: 50, borderRadius: 25, alignItems: 'center', justifyContent: 'center' },
  recipesCircle: { backgroundColor: '#FFF6B8' },
  logoutCircle: { backgroundColor: '#FFF1E8' },
  optionIcon: { width: 34, height: 34 },
  optionCopy: { flex: 1, gap: 6 },
  optionTitle: { color: '#512013', fontFamily: 'Inter_800ExtraBold', fontSize: 17, lineHeight: 22 },
  optionDescription: { color: '#81818A', fontFamily: 'Inter_400Regular', fontSize: 12, lineHeight: 17 },
  chevron: { width: 14, height: 20 },
  pressed: { opacity: 0.7 },
  notice: { color: '#512013', fontFamily: 'Inter_400Regular', fontSize: 13, lineHeight: 20, marginTop: 18 },
});


