import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  contenedor: {
    flex: 1,
    backgroundColor: "#FFFBF0",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  botonCircular: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#552414",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 3,
  },
  logoContenedor: {
    flexDirection: "row",
    alignItems: "center",
    gap: -4,
  },
  estadoContenedor: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FFFBF0",
  },
  estadoContenedorError: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
    backgroundColor: "#FFFBF0",
  },
  estadoTexto: {
    marginTop: 12,
    textAlign: "center",
    color: "#552414",
  },
  estadoBotonVolver: {
    marginTop: 16,
  },
  estadoBotonVolverTexto: {
    color: "#FF4F0A",
    fontWeight: "600",
  },
  imagen: {
    width: "auto",
    height: 220,
    marginHorizontal: 7,
    borderRadius: 18,
  },
  encabezadoFila:{
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 6,
    marginTop: 4,
  },
  encabezadoTextos:{
    flex:1,
  },
  titulo: {
    fontSize: 30,
    fontFamily: "Kavoon_400Regular",
    color: "#552414",
  },
  descripcion: {
    lineHeight: 22,
    color: "#9C8B7A",
    fontSize: 12,
  },
  lineaVertical: {
    width: 1,
    height: 40,
    alignSelf: "center",
    backgroundColor: "#D9C8BC",
    marginLeft: 4,
    marginRight: 16,
  },
  encabezadoDerecha: {
    justifyContent: "center",
    alignItems: "center",
    width: 28,
  },
  metaFila: {
    flexDirection: "row",
    gap: 10,
    marginHorizontal: 16,
    marginTop: 12,
  },
  metaPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#FBEEDC",
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  metaTexto: {
    fontSize: 13,
    fontWeight: "700",
    color: "#552414",
  },
  ingredientesTitulo: {
    fontSize: 16,
    fontWeight: "900",
    marginBottom: 16,
    color: "#552414",
  },
  pasoTexto: {
    flex: 1,
    fontSize: 13,
    color: "#756B64",
    lineHeight: 14,
  },
  tipsTexto: {
    fontSize: 13,
    lineHeight: 20,
    color: "#756B64",
  },
  ingredientesCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    marginHorizontal: 8,
    marginTop: 16,
    paddingHorizontal: 8,
    paddingTop: 4,
    shadowColor: "#552414",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 4,
  },
  ingredientesGrid:{
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  ingredienteItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    width: "48%",
    marginBottom: 18,
  },
  ingredienteBullet: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: "#E5E0D8",
    marginTop: 2,
  },
  ingredienteTexto: {
    flex: 1,
    fontSize: 13,
    color: "#756B64",
    lineHeight: 14,
  },

  preparacionCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    marginHorizontal: 8,
    marginTop: 16,
    paddingHorizontal: 8,
    paddingTop: 4,
    shadowColor: "#552414",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 4,
  },
  preparacionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  preparacionTitulo: {
    fontSize: 16,
    fontWeight: "900",
    color: "#552414",
  },
  botonAudio: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: "#FF4F0A",
    justifyContent: "center",
    alignItems: "center",
  },
  pasoFila: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    marginBottom: 14,
  },
  pasoNumero: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#FF4F0A",
    justifyContent: "center",
    alignItems: "center",
  },
  pasoNumeroTexto: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "700",
  },
  logoSombrero: {
    width: 65,
    height: 53,
    marginRight: -25,
  },
  logoTitulo: {
    width: 170,
    height: 50,
    marginLeft: -20,
  },
  tipsCard: {
    backgroundColor: "#FBEEDC",
    borderRadius: 16,
    borderLeftWidth: 4,
    borderLeftColor: "#FF4F0A",
    marginHorizontal: 8,
    marginTop: 16,
    marginBottom: 24,
    padding: 16,
  },
  tipsTitulo: {
    fontSize: 16,
    fontWeight: "900",
    color: "#552414",
  },
  tipsEncabezado: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  valoracionBloque: {
    alignItems: "center",
    justifyContent: "center",
    width: 84,
    overflow: "visible",
  },
  valoracionPresionado: {
    opacity: 0.6,
    transform: [{ scale: 0.95 }],
  },
});