import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  contenedor: {
    flex: 1,
    backgroundColor: "#FFFCF2",
  },
  scrollContenido: {
    width: "100%",
    maxWidth: 640,
    alignSelf: "center",
    paddingHorizontal: 16,
    paddingBottom: 24,
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 8,
    paddingHorizontal: 16,
    minHeight: 56,
  },
  botonAtras: {
    position: "absolute",
    left: 16,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    elevation: 3,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
  },
  logoFila: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    gap: -4,
  },
  logoSombrero: {
    width: 65,
    height: 53,
    marginRight: -25,
  },
  logoTitulo: {
    width: 170,
    height: 50,
    marginLeft: -20,
  },
  tituloFila: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
    gap: 6,
  },
  hojaTitulo: {
    width: 30,
    height: 30,
  },
  titulo: {
    fontFamily: "Coiny_400Regular",
    fontSize: 27,
    color: "#552414",
    textAlign: "center",
  },
  subtitulo: {
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    color: "#9C8B7A",
    textAlign: "center",
    marginTop: 2,
    marginBottom: 16,
  },
  tarjeta: {
    flexDirection: "column",
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 12,
    marginBottom: 14,
    gap: 10,
    elevation: 3,
    shadowColor: "#402610",
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
  },
  filaSuperior: {
    flexDirection: "row",
    gap: 12,
  },
  imagen: {
    width: "40%",
    alignSelf: "stretch",
    minHeight: 120,
    borderRadius: 16,
    backgroundColor: "#FBEEDC",
  },
  tarjetaContenido: {
    flex: 1,
    minWidth: 0,
  },
  tarjetaHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
  },
  tarjetaTitulo: {
    flex: 1,
    fontFamily: "Inter_800ExtraBold",
    fontSize: 17,
    color: "#552414",
    lineHeight: 21,
  },
  corazon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#F0E6D8",
    alignItems: "center",
    justifyContent: "center",
    elevation: 2,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
  },
  descripcion: {
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    color: "#7A6A5E",
    lineHeight: 17,
    marginTop: 6,
  },
  tienesBox: {
    backgroundColor: "#EEF7E8",
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  tienesHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 6,
  },
  tienesLabel: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 15,
    color: "#552414",
  },
  chipsFila: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  chip: {
    flexGrow: 1,
    backgroundColor: "#E2F3D5",
    borderWidth: 1,
    borderColor: "#80B94B",
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  chipTexto: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    color: "#2E7D32",
    textAlign: "center",
  },
  metaFila: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 8,
    marginTop: 10,
  },
  metaItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#FBEEDC",
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  metaTexto: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: "#552414",
  },
  contador: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 13,
    color: "#552414",
    textAlign: "left",
    marginBottom: 8,
  },
  insignia: {
    alignSelf: "flex-start",
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 3,
    marginTop: 6,
  },
  insigniaCompleta: {
    backgroundColor: "#2E7D32",
  },
  insigniaParcial: {
    backgroundColor: "#E65100",
  },
  insigniaTexto: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: "#FFFFFF",
  },
  estadoContenedor: {
    alignItems: "center",
    paddingVertical: 32,
    gap: 8,
  },
  estadoTitulo: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 16,
    color: "#552414",
    textAlign: "center",
  },
  estadoTexto: {
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    color: "#9C8B7A",
    textAlign: "center",
  },
  botonReintentar: {
    backgroundColor: "#552414",
    borderRadius: 14,
    paddingHorizontal: 18,
    paddingVertical: 10,
    marginTop: 8,
  },
  botonReintentarTexto: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 14,
    color: "#FFFFFF",
  },
  cargarMasContenedor: {
    alignItems: "center",
    marginVertical: 4,
  },
});
