import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  contenedor: {
    flex: 1,
    backgroundColor: "#FFFCF2",
  },
  scrollContenido: {
    paddingHorizontal: 16,
    paddingBottom: 24,
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 8,
    paddingHorizontal: 16,
    minHeight: 56,
  },
  botonAtras: {
    position: "absolute",
    left: 16,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    elevation: 3,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
  },
  logoFila: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  logoSombrero: {
    width: 44,
    height: 44,
  },
  logoTitulo: {
    width: 150,
    height: 40,
    marginLeft: 4,
  },
  tituloFila: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
    gap: 6,
  },
  hojaTitulo: {
    width: 30,
    height: 30,
  },
  titulo: {
    fontFamily: "Coiny_400Regular",
    fontSize: 27,
    color: "#552414",
    textAlign: "center",
  },
  subtitulo: {
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    color: "#9C8B7A",
    textAlign: "center",
    marginTop: 2,
    marginBottom: 16,
  },
  tarjeta: {
    flexDirection: "row",
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 12,
    marginBottom: 14,
    gap: 12,
    elevation: 3,
    shadowColor: "#402610",
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
  },
  imagen: {
    width: 108,
    height: 150,
    borderRadius: 16,
    backgroundColor: "#FBEEDC",
  },
  tarjetaContenido: {
    flex: 1,
    minWidth: 0,
  },
  tarjetaHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
  },
  tarjetaTitulo: {
    flex: 1,
    fontFamily: "Inter_800ExtraBold",
    fontSize: 17,
    color: "#552414",
    lineHeight: 21,
  },
  corazon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#F0E6D8",
    alignItems: "center",
    justifyContent: "center",
    elevation: 2,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
  },
  descripcion: {
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    color: "#7A6A5E",
    lineHeight: 17,
    marginTop: 2,
  },
  tienesBox: {
    backgroundColor: "#DFF0C2",
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginTop: 8,
  },
  tienesLabel: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 13,
    color: "#552414",
    marginBottom: 6,
  },
  chipsFila: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  chip: {
    backgroundColor: "#7CB342",
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  chipTexto: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    color: "#FFFFFF",
  },
  metaFila: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginTop: 8,
  },
  metaItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  metaTexto: {
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    color: "#9C8B7A",
  },
});
