import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#FFFBF0" },
  content: {
    flexGrow: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 22,
    paddingVertical: 24,
  },
  page: { width: "100%", maxWidth: 390 },
  backButton: { width: 50, height: 50, zIndex: 1 },
  backIcon: { width: "100%", height: "100%" },
  brand: { alignItems: "center", marginTop: -18, marginBottom: 20 },
  logoRow: { width: "100%", flexDirection: "row", alignItems: "center" },
  chefHat: { width: "39%", aspectRatio: 143 / 141, marginRight: "-8%" },
  titleLogo: { width: "69%", aspectRatio: 250 / 106 },
  taglineRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "flex-end",
    width: "90%",
    marginTop: -6,
    marginBottom: 8,
  },
  taglineText: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 9,
    transform: [{ rotate: "-8deg" }],
  },
  taglineFirstLine: {
    color: "#5B1D12",
    fontFamily: "Lobster_400Regular",
    fontSize: 26,
    lineHeight: 30,
    textAlign: "center",
  },
  taglineSecondLine: {
    color: "#5B1D12",
    fontFamily: "Lobster_400Regular",
    fontSize: 26,
    lineHeight: 30,
    marginLeft: 24,
    textAlign: "center",
  },
  taglineHeart: {
    width: 40,
    height: 40,
    flexShrink: 0,
    marginLeft: 5,
    transform: [{ rotate: "8deg" }],
  },
  illustration: { width: "100%", position: "relative" },
  chef: { width: "100%", aspectRatio: 580 / 410 },
  community: {
    position: "absolute",
    right: 0,
    top: "5%",
    width: "36%",
    alignItems: "center",
  },
  communityText: {
    color: "#512013",
    fontFamily: "Lobster_400Regular",
    fontSize: 17,
    lineHeight: 21,
    textAlign: "center",
    transform: [{ rotate: "-8deg" }],
  },
  communityHeart: {
    width: 26,
    height: 26,
    marginTop: 4,
    transform: [{ rotate: "8deg" }],
  },
  heading: {
    color: "#5B1D12",
    fontFamily: "Inter_800ExtraBold",
    fontSize: 33,
    lineHeight: 40,
    marginTop: 4,
    textAlign: "center",
  },
  subtitle: {
    color: "#7C736C",
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 21,
    marginTop: 6,
    paddingHorizontal: 16,
    textAlign: "center",
  },
  form: { gap: 14, width: "100%" },
  inputGroup: { gap: 5 },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "transparent",
    paddingLeft: 8,
    paddingRight: 8,
    paddingVertical: 8,
    boxShadow: "0px 4px 10px rgba(64, 38, 16, 0.06)",
  },
  inputRowFocused: {
    borderColor: "#FF5008",
  },
  inputRowError: {
    borderColor: "#FF4F0A",
  },
  inputIcon: { width: 40, height: 40, flexShrink: 0 },
  inputField: {
    flex: 1,
    minWidth: 0,
    marginLeft: 10,
    paddingVertical: 6,
    color: "#512013",
    fontFamily: "Inter_400Regular",
    fontSize: 15,
    lineHeight: 22,
  },
  errorText: {
    color: "#FF4F0A",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 16,
    paddingHorizontal: 4,
  },
  passwordToggle: {
    width: 36,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    flexShrink: 0,
  },
  passwordToggleIcon: {
    width: 22,
    height: 22,
  },
  termsGroup: { gap: 5, marginTop: 2 },
  termsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 4,
    paddingHorizontal: 4,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 6,
    borderWidth: 1.8,
    borderColor: "#A12D28",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxChecked: {
    backgroundColor: "#FF4F0A",
    borderColor: "#FF4F0A",
  },
  checkmark: {
    color: "#FFFFFF",
    fontFamily: "Inter_600SemiBold",
    fontSize: 13,
    lineHeight: 15,
  },
  termsText: {
    flex: 1,
    color: "#512013",
    fontFamily: "Inter_400Regular",
    fontSize: 14.5,
    lineHeight: 20,
  },
  termsLink: {
    color: "#FF4F0A",
    fontFamily: "Inter_600SemiBold",
    textDecorationLine: "underline",
  },
  buttonArrow: { width: 22, height: 22 },
  footer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    marginTop: 12,
    alignSelf: "stretch",
    minHeight: 44,
    paddingHorizontal: 8,
  },
  footerText: {
    color: "#512013",
    fontFamily: "Inter_400Regular",
    fontSize: 14.5,
    lineHeight: 20,
  },
  footerLink: {
    color: "#FF4F0A",
    fontFamily: "Inter_600SemiBold",
    fontSize: 14.5,
    lineHeight: 20,
  },
  bottomLeafLeft: {
    position: "absolute",
    left: 10,
    bottom: 8,
    width: 42,
    height: 42,
    zIndex: 0,
  },
  bottomLeafRight: {
    position: "absolute",
    right: 10,
    bottom: 8,
    width: 42,
    height: 42,
    zIndex: 0,
    transform: [{ scaleX: -1 }],
  },
  pressed: { opacity: 0.7 },
});

export function getRegisterStyles(availableHeight: number) {
  if (availableHeight >= 900) return styles;

  return {
    ...styles,
    content: { ...styles.content, paddingVertical: 12 },
    backButton: { ...styles.backButton, width: 44, height: 44 },
    brand: { ...styles.brand, marginBottom: 12 },
    logoRow: { ...styles.logoRow, width: "85%" as const },
    taglineRow: { ...styles.taglineRow, marginBottom: 4 },
    taglineText: { ...styles.taglineText, paddingVertical: 5 },
    taglineFirstLine: {
      ...styles.taglineFirstLine,
      fontSize: 24,
      lineHeight: 27,
    },
    taglineSecondLine: {
      ...styles.taglineSecondLine,
      fontSize: 24,
      lineHeight: 27,
    },
    illustration: { ...styles.illustration, width: "92%" as const },
    chef: {
      ...styles.chef,
      height: Math.max(70, Math.min(160, availableHeight - 630)),
      aspectRatio: undefined,
    },
    community: { ...styles.community, width: "34%" as const },
    communityText: { ...styles.communityText, fontSize: 15, lineHeight: 18 },
    communityHeart: { ...styles.communityHeart, width: 22, height: 22 },
    heading: { ...styles.heading, fontSize: 28, lineHeight: 34 },
    subtitle: { ...styles.subtitle, fontSize: 14, lineHeight: 19, marginTop: 4 },
    form: { ...styles.form, gap: 11 },
    inputRow: { ...styles.inputRow, paddingVertical: 6 },
    inputIcon: { ...styles.inputIcon, width: 36, height: 36 },
    inputField: { ...styles.inputField, fontSize: 15 },
    footer: { ...styles.footer, marginTop: 8, minHeight: 40 },
  };
}
