import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#FFFBF0" },
  content: {
    flexGrow: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 22,
    paddingVertical: 24,
  },
  page: { width: "100%", maxWidth: 390 },
  backButton: { width: 52, height: 52, zIndex: 1 },
  backIcon: { width: "100%", height: "100%" },
  brand: { alignItems: "center", marginTop: -18, marginBottom: 24 },
  logoRow: { width: "100%", flexDirection: "row", alignItems: "center" },
  chefHat: { width: "39%", aspectRatio: 143 / 141, marginRight: "-8%" },
  titleLogo: { width: "69%", aspectRatio: 250 / 106 },
  taglineRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "flex-end",
    width: "90%",
    marginTop: -6,
    marginBottom: 8,
  },
  taglineText: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 9,
    transform: [{ rotate: "-8deg" }],
  },
  taglineFirstLine: {
    color: "#5B1D12",
    fontFamily: "Lobster_400Regular",
    fontSize: 26,
    lineHeight: 30,
    textAlign: "center",
  },
  taglineSecondLine: {
    color: "#5B1D12",
    fontFamily: "Lobster_400Regular",
    fontSize: 26,
    lineHeight: 30,
    marginLeft: 24,
    textAlign: "center",
  },
  taglineHeart: {
    width: 40,
    height: 40,
    flexShrink: 0,
    marginLeft: 5,
    transform: [{ rotate: "8deg" }],
  },
  chef: { width: "90%", aspectRatio: 580 / 410 },
  headingRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    marginTop: 3,
  },
  heading: {
    color: "#5B1D12",
    fontFamily: "Inter_800ExtraBold",
    fontSize: 29,
    lineHeight: 38,
    flexShrink: 1,
    textAlign: "center",
  },
  headingLeaves: { width: 32, height: 38 },
  formCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 21,
    paddingHorizontal: 17,
    paddingVertical: 20,
    boxShadow: "0px 4px 10px rgba(64, 38, 16, 0.07)",
  },
  form: { gap: 14, width: "100%" },
  inputGroup: { gap: 6 },
  inputLabel: {
    color: "#512013",
    fontFamily: "Inter_600SemiBold",
    fontSize: 14,
    lineHeight: 20,
  },
  input: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "#E0E1E6",
    paddingHorizontal: 16,
    paddingVertical: 14,
    color: "#512013",
    fontFamily: "Inter_400Regular",
    fontSize: 16,
    lineHeight: 22,
  },
  inputFocused: {
    borderColor: "#FF5008",
  },
  inputError: {
    borderColor: "#FF4F0A",
  },
  errorText: {
    color: "#FF4F0A",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 16,
  },
  passwordContainer: {
    position: "relative",
    justifyContent: "center",
  },
  passwordToggle: {
    position: "absolute",
    right: 16,
    top: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
    width: 32,
  },
  passwordToggleIcon: {
    width: 22,
    height: 22,
  },
  submitButton: {
    backgroundColor: "#FF4F0A",
    paddingVertical: 16,
    borderRadius: 30,
    alignItems: "center",
    alignSelf: "stretch",
    marginTop: 8,
  },
  submitButtonText: {
    color: "#FFFFFF",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  loginLink: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    marginTop: 14,
    alignSelf: "stretch",
    minHeight: 48,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderWidth: 1,
    borderColor: "#FF5008",
    borderRadius: 28,
  },
  loginLinkText: {
    color: "#FF5008",
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 20,
  },
  loginLinkButton: {
    color: "#FF5008",
    fontFamily: "Inter_600SemiBold",
    fontSize: 14,
    lineHeight: 20,
  },
  pressed: { opacity: 0.7 },
});

export function getRegisterStyles(availableHeight: number) {
  if (availableHeight >= 900) return styles;

  return {
    ...styles,
    content: { ...styles.content, paddingVertical: 12 },
    backButton: { ...styles.backButton, width: 44, height: 44 },
    brand: { ...styles.brand, marginBottom: 10 },
    logoRow: { ...styles.logoRow, width: "85%" as const },
    taglineRow: { ...styles.taglineRow, marginBottom: 4 },
    taglineText: { ...styles.taglineText, paddingVertical: 5 },
    taglineFirstLine: {
      ...styles.taglineFirstLine,
      fontSize: 24,
      lineHeight: 27,
    },
    taglineSecondLine: {
      ...styles.taglineSecondLine,
      fontSize: 24,
      lineHeight: 27,
    },
    chef: {
      ...styles.chef,
      width: "90%" as const,
      height: Math.max(80, Math.min(160, availableHeight - 620)),
      aspectRatio: undefined,
    },
    heading: { ...styles.heading, fontSize: 27, lineHeight: 34 },
    form: { ...styles.form, gap: 10 },
    formCard: { ...styles.formCard, paddingHorizontal: 14, paddingVertical: 16 },
    inputGroup: { ...styles.inputGroup, gap: 4 },
    input: {
      ...styles.input,
      paddingVertical: 12,
      fontSize: 15,
    },
    submitButton: {
      ...styles.submitButton,
      paddingVertical: 14,
    },
  };
}
